# Generated by Django 3.2.9 on 2021-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d/')),
            ],
        ),
    ]
